name: Build and Start Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Start Server
      run: |
        cd server
        npm install
        npm start &

    - name: Build and Start Client
      run: |
        cd client
        npm install
        npm run build
        npm start &

    - name: Build and Start Truck Dashboard
      run: |
        cd truck-dashboard
        npm install
        npm run build
        npm start &
